import colors from './colors';

const theme = {
  fontSize: {
    'xxsmall': 12,
    'xsmall': 14,
    'small': 16,
    'medium': 18,
    'large': 20,
    'xlarge': 22,
    'xxlarge': 24,
  },
  size: {
    'xxsmall': 10,
    'xsmall': 12,
    'small': 14,
    'medium': 16,
    'large': 18,
    'xlarge': 20,
    'xxlarge': 22,
  },
  buttonWidth: {
    'xxsmall': 90,
    'xsmall': 100,
    'small': 120,
    'medium': 140,
    'large': 150,
    'xlarge': 160,
    'xxlarge': 180,
  },
  iconSize: {
    'xxsmall': 16,
    'xsmall': 18,
    'small': 22,
    'medium': 26,
    'large': 28,
    'xlarge': 32,
    'xxlarge': 36,
  },
  avatarSize: {
    'xxsmall': 60,
    'xsmall': 70,
    'small': 80,
    'medium': 90,
    'large': 110,
    'xlarge': 120,
    'xxlarge': 140,
  },
  badgeSize: {
    'xxsmall': 10,
    'xsmall': 11,
    'small': 12,
    'medium': 13,
    'large': 14,
    'xlarge': 16,
    'xxlarge': 18,
  },
  miniBadgeSize: {
    'xxsmall': 10,
    'xsmall': 11,
    'small': 12,
    'medium': 15,
    'large': 17,
    'xlarge': 19,
    'xxlarge': 21,
  },
  space: {
    'none': 0,
    'xxsmall': 2,
    'xsmall': 4,
    'small': 5,
    'medium': 7.5,
    'large': 10,
    'xlarge': 15,
    'xxlarge': 20,
  },
  textColor: {
    'default': colors.black[300],
    'heading': colors.black[800],
    'subtle': colors.black[100],
    'disabled': colors.bluegrey[400],
    'white': colors.blue[50],
  },
  brandColor: {
    'primary': colors.blue[600],
    'secondary': colors.blue[100],
    'tertiary': colors.red[600],
    'background': '#f8f8f8',
    'disabled': colors.bluegrey[100],
    'white': colors.blue[50],
    'clearWhite': '#fff',
  },
};

export default theme;

