export interface themeType {
  fontSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  size: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  actionButtonSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  buttonSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  buttonWidth: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  iconSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  avatarSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  badgeSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  miniBadgeSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  listItemSpace: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  space: {
    'none': number,
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  layoutSpace: {
    'none': number,
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  indicatorSize: {
    'xxsmall': number,
    'xsmall': number,
    'small': number,
    'medium': number,
    'large': number,
    'xlarge': number,
    'xxlarge': number,
  },
  fontFamily: {
    'heading': string,
    'text': string,
  },
  textColor: {
    'default': string,
    'heading': string,
    'subtle': string,
    'grey': string,
    'disabled': string,
    'white': string,
  },
  brandColor: {
    'primary': string,
    'secondary': string,
    'tertiary': string,
    'background': string,
    'disabled': string,
    'white': string,
    'semitransparent': string,
    'grey': string,
    'clearWhite': string,
    'outline': string,
  },
}
